"""
Static SEO pages for Knowledge Arm briefs.

Pure renderer: every output is a deterministic function of
``config/briefs_registry.json`` (no clock, no environment), so a committed
page can be checked for freshness by re-rendering and comparing.

Used by ``scripts/build_brief_pages.py``; covered by
``tests/test_briefs_pages.py``.

Generated pages live one level down (``website/briefs/<id>.html``) and carry
``<base href="../">`` so the shared site chrome (chrome.js relative links,
CSS, JS, brand assets) resolves against the site root.
"""

from __future__ import annotations

import html
import json
from typing import Any, Dict, Iterable, List

SITE = "https://talaix.com"

KIND_LABELS = {
    "framework_explainer": "Framework explainer",
    "evidence_brief": "Evidence brief",
}

SITEMAP_BEGIN = "  <!-- BRIEFS:BEGIN (generated by scripts/build_brief_pages.py — edit the registry, not this block) -->"
SITEMAP_END = "  <!-- BRIEFS:END -->"


def esc(value: Any) -> str:
    return html.escape("" if value is None else str(value), quote=True)


def page_url(brief_id: str) -> str:
    return f"{SITE}/briefs/{brief_id}.html"


def _kind_label(kind: str) -> str:
    return KIND_LABELS.get(kind, kind)


def _meta_description(summary: str) -> str:
    """Meta descriptions read best under ~160 chars; cut on a word boundary."""
    text = " ".join((summary or "").split())
    if len(text) <= 158:
        return text
    return text[:155].rsplit(" ", 1)[0].rstrip(",;:.") + "…"


def _json_ld(brief: Dict[str, Any]) -> str:
    url = page_url(brief["id"])
    payload = {
        "@context": "https://schema.org",
        "@type": "Article",
        "headline": brief.get("title"),
        "description": brief.get("summary"),
        "inLanguage": "en",
        "datePublished": brief.get("date"),
        "dateModified": brief.get("date"),
        "articleSection": _kind_label(brief.get("kind", "")),
        "isAccessibleForFree": True,
        "author": {
            "@type": "Organization",
            "name": "Talaix Knowledge Arm",
            "url": f"{SITE}/academy.html?mode=briefs",
        },
        "publisher": {
            "@type": "Organization",
            "name": "Talaix",
            "url": SITE,
            "logo": {
                "@type": "ImageObject",
                "url": f"{SITE}/assets/brand/logo-master.png",
            },
        },
        "mainEntityOfPage": {"@type": "WebPage", "@id": url},
    }
    return json.dumps(payload, ensure_ascii=False, indent=2)


def _sections_html(brief: Dict[str, Any]) -> str:
    parts: List[str] = []
    for section in brief.get("sections", []):
        body = esc(section.get("body")).replace("\n", "<br>\n")
        parts.append(f"<h2>{esc(section.get('heading'))}</h2>\n<p>{body}</p>")
    return "\n".join(parts)


def _sources_html(brief: Dict[str, Any]) -> str:
    rows: List[str] = []
    for source in brief.get("sources", []):
        rows.append(
            "<tr>"
            f"<td>{esc(source.get('name'))}</td>"
            f"<td>{esc(source.get('date')) if source.get('date') else '—'}</td>"
            f"<td><span class=\"chip chip-{esc(str(source.get('claim_status', '')).lower())}\">{esc(source.get('claim_status'))}</span></td>"
            f"<td><a class=\"text-link\" href=\"{esc(source.get('url'))}\" target=\"_blank\" rel=\"noopener\">Source →</a></td>"
            "</tr>"
        )
    if not rows:
        rows.append('<tr><td colspan="4" class="muted small">No sources listed.</td></tr>')
    return "\n".join(rows)


def _related_tools_html(brief: Dict[str, Any]) -> str:
    tools = brief.get("related_tools") or []
    if not tools:
        return ""
    links = "".join(
        f'<a class="btn-secondary btn-sm" href="{esc(t.get("href"))}" '
        f'style="margin-right:8px; margin-bottom:8px; display:inline-block;">{esc(t.get("label"))}</a>'
        for t in tools
    )
    return f"<h2>Related tools</h2>\n<p>{links}</p>"


def _related_glossary_html(brief: Dict[str, Any]) -> str:
    terms = brief.get("related_glossary") or []
    if not terms:
        return ""
    chips = " ".join(
        f'<a class="chip chip-documented" href="academy.html" style="text-decoration:none;">{esc(t)}</a>'
        for t in terms
    )
    return f'<p style="margin-top:16px;"><strong>Related glossary:</strong> {chips}</p>'


def render_brief_page(brief: Dict[str, Any]) -> str:
    """Render the full static HTML page for one published brief."""
    url = page_url(brief["id"])
    title = brief.get("title", "")
    kind = brief.get("kind", "")
    kind_label = _kind_label(kind)
    date = brief.get("date", "")
    sources = brief.get("sources", [])
    source_word = "source" if len(sources) == 1 else "sources"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <base href="../">
    <title>{esc(title)} — Talaix Knowledge Arm</title>
    <meta name="description" content="{esc(_meta_description(brief.get('summary', '')))}">
    <link rel="canonical" href="{esc(url)}">
    <meta property="og:type" content="article">
    <meta property="og:title" content="{esc(title)}">
    <meta property="og:description" content="{esc(brief.get('summary', ''))}">
    <meta property="og:url" content="{esc(url)}">
    <meta property="og:site_name" content="Talaix">
    <meta property="article:published_time" content="{esc(date)}">
    <meta name="twitter:card" content="summary">
    <link rel="icon" type="image/png" sizes="32x32" href="assets/brand/favicon-32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="assets/brand/favicon-16.png">
    <link rel="apple-touch-icon" href="assets/brand/apple-touch-icon.png">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Space+Grotesk:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="css/style.css">
    <script type="application/ld+json">
{_json_ld(brief)}
    </script>
</head>
<body data-page="briefs">
    <div id="site-header"></div>

    <main class="page-main">
        <div class="container">
            <p><a class="text-link" href="academy.html?mode=briefs">← All Knowledge Arm briefs</a></p>

            <article>
                <p><span class="chip chip-{esc(kind)}">{esc(kind_label)}</span></p>
                <h1>{esc(title)}</h1>
                <p class="muted small">{esc(date)} · {esc(kind_label)} · {len(sources)} {source_word}</p>
                <p class="page-lead">{esc(brief.get('summary', ''))}</p>

                {_sections_html(brief)}

                <h2>Sources</h2>
                <div class="table-scroll">
                    <table class="data-table">
                        <thead>
                            <tr><th>Name</th><th>Date</th><th>Status</th><th>Link</th></tr>
                        </thead>
                        <tbody>
                            {_sources_html(brief)}
                        </tbody>
                    </table>
                </div>

                {_related_tools_html(brief)}
                {_related_glossary_html(brief)}

                <div class="notice notice-info" style="margin-top:32px;">
                    <strong>Sourcing rules.</strong> We use open sources only. Every fact is
                    linked to a publisher with a date where available. News items are REPORTED;
                    official documents are DOCUMENTED. "Talaix view" analysis is explicitly
                    labelled. A beat with nothing verifiable is stated, never filled. No
                    predictions as fact, no invented statistics, no paywalled sources.
                    <a class="text-link" href="contact.html">Suggest an open source →</a>
                </div>
            </article>
        </div>
    </main>

    <div id="site-footer"></div>

    <script src="js/api.js"></script>
    <script src="js/chrome.js"></script>
</body>
</html>
"""


def sitemap_block(published: Iterable[Dict[str, Any]]) -> str:
    """The generated sitemap block (markers included) for published briefs."""
    lines = [SITEMAP_BEGIN]
    for brief in published:
        lines.append("  <url>")
        lines.append(f"    <loc>{esc(page_url(brief['id']))}</loc>")
        lines.append(f"    <lastmod>{esc(brief.get('date', ''))}</lastmod>")
        lines.append("    <changefreq>yearly</changefreq>")
        lines.append("    <priority>0.7</priority>")
        lines.append("  </url>")
    lines.append(SITEMAP_END)
    return "\n".join(lines)


def update_sitemap(xml: str, published: Iterable[Dict[str, Any]]) -> str:
    """Insert or replace the generated briefs block inside sitemap XML."""
    block = sitemap_block(published)
    if SITEMAP_BEGIN in xml and SITEMAP_END in xml:
        head = xml[: xml.index(SITEMAP_BEGIN)]
        tail = xml[xml.index(SITEMAP_END) + len(SITEMAP_END):]
        return head + block + tail
    closing = "</urlset>"
    if closing not in xml:
        raise ValueError("sitemap is missing </urlset>")
    return xml.replace(closing, block + "\n" + closing)
